src/main/java/com/levelUpToast/levelUpToast/config/InitData.java
src/main/java/com/levelUpToast/levelUpToast/config/session/SessionConst.java
src/main/java/com/levelUpToast/levelUpToast/config/session/form/SessionForm.java
src/main/java/com/levelUpToast/levelUpToast/domain/login/loginServiceImpl/SimpleLoginService.java
src/main/java/com/levelUpToast/levelUpToast/domain/login/loginServiceInterface/LoginService.java
src/main/java/com/levelUpToast/levelUpToast/domain/member/Member.java
src/main/java/com/levelUpToast/levelUpToast/rest/login/LoginController.java

- domain : Service 관련 로직 및 객체 클래스 구성 package 
ex) loginService , Member 
- rest : rest API Controller 관련 package
ex) loginController
위와 같은 형식으로 향후 프로젝트 진행 예정

😎프로젝트 기본 package 구성

---

src/main/java/com/levelUpToast/levelUpToast/domain/member/Authority.java
src/main/java/com/levelUpToast/levelUpToast/domain/member/Member.java

Member Class 내부 프로퍼티 추가 진행 ( 미완 )
Member Class 의 Authority를 위한 Authority enum class 생성

😎 Member Class 프로퍼티 와 Authority 구성

---

src/main/java/com/levelUpToast/levelUpToast/LevelUpToastApplication.java
src/main/java/com/levelUpToast/levelUpToast/config/InitData.java
src/main/java/com/levelUpToast/levelUpToast/config/exception/LevelUpToastEx.java
src/main/java/com/levelUpToast/levelUpToast/config/session/SessionConst.java
src/main/java/com/levelUpToast/levelUpToast/config/session/form/SessionForm.java
src/main/java/com/levelUpToast/levelUpToast/config/token/tokenManager/tokenManagerImpl/SimpleTokenManager.java
src/main/java/com/levelUpToast/levelUpToast/config/token/tokenManager/tokenManagerInf/TokenManager.java
src/main/java/com/levelUpToast/levelUpToast/domain/dataForm/login/LoginForm.java
src/main/java/com/levelUpToast/levelUpToast/domain/dataForm/login/LoginRequestFrom.java
src/main/java/com/levelUpToast/levelUpToast/domain/dataForm/login/LoginResponseForm.java
src/main/java/com/levelUpToast/levelUpToast/domain/member/Authority.java
src/main/java/com/levelUpToast/levelUpToast/domain/member/Member.java
src/main/java/com/levelUpToast/levelUpToast/domain/repository/memberRepository/memberRepositoryImpl/MemoryMemberRepository.java
src/main/java/com/levelUpToast/levelUpToast/domain/repository/memberRepository/memberRepositoryInf/MemberRepository.java
src/main/java/com/levelUpToast/levelUpToast/rest/login/LoginController.java
src/main/java/com/levelUpToast/levelUpToast/service/login/loginServiceImpl/SimpleLoginService.java
src/main/java/com/levelUpToast/levelUpToast/service/login/loginServiceInterface/LoginService.java

<h2> 로그인 실패 케이스 실행 화면 </h2>
<h3> < 미존재 ID 요청시 > </h3>
( postman )
( 스프링 부트 내부 콘솔 )
<h3> < 틀린 PW로 요청시 > </h3>
( postman )
( 스프링 부터 내부 콘솔 )
---------------
<h2> 로그인 성공 케이스 실행 화면 </h2>
<h3> < 로그인 성공 > </h3>
( postman )
( 스프링 부터 내부 콘솔 )
---------------
<h2> 현재 로그인 가능 initData </h2>
---------------
<h2> 공지 </h2>
* session이 아닌 내부적  UUID 값인 토큰을 생성하여 사용자 인증한다. ( TokenManager )
* DetailCode를 사용하기 위해 LevelUpToastEx 를 통해 예외 처리 및 예외 메세지 사용하여 예외처리 한다. 
* 참고 문헌 [ Exception 만들기 ](https://devbox.tistory.com/entry/Java-%EC%98%88%EC%99%B8-%EB%A7%8C%EB%93%A4%EA%B8%B0)

😎 로그인 서비스 구현 완료 

---

src/main/java/com/levelUpToast/levelUpToast/domain/dataForm/img/ImgRequestForm.java
src/main/java/com/levelUpToast/levelUpToast/domain/dataForm/img/ImgSaveResponseForm.java
src/main/java/com/levelUpToast/levelUpToast/domain/img/ImgItem.java
src/main/java/com/levelUpToast/levelUpToast/domain/member/Authority.java
src/main/java/com/levelUpToast/levelUpToast/domain/member/Member.java
src/main/java/com/levelUpToast/levelUpToast/domain/repository/imgRepository/imgRepositoryImpl/MemoryImgRepository.java
src/main/java/com/levelUpToast/levelUpToast/domain/repository/imgRepository/imgRepositoryInf/ImgRepository.java
src/main/java/com/levelUpToast/levelUpToast/rest/img/ImgController.java
src/main/java/com/levelUpToast/levelUpToast/service/img/imgServiceImpl/ImgService_Perriy_MacBook.java
src/main/java/com/levelUpToast/levelUpToast/service/img/imgServiceInf/ImgService.java
src/main/resources/application.properties

이미지 컨트롤러 추가
* /img/123-123.png  ( 이미지 요청 )
* /img ( 이미지 저장 )
현재 이미지 반환 상태 ( 바이너리 형태 )
* 확인 사항 
application.properties 이미지 저장 경로 추가 설정 필요

😎 이미지 처리 시스템 추가 

---

src/main/resources/application.properties

refactor (application.properties) : folder location

---

src/main/java/com/levelUpToast/levelUpToast/rest/img/ImgController.java

😎 이미지 저장 서비스 추가

---

src/main/java/com/levelUpToast/levelUpToast/domain/product/ProductDetail.java
src/main/java/com/levelUpToast/levelUpToast/domain/product/buyoption/BuyOption.java
src/main/java/com/levelUpToast/levelUpToast/domain/product/fundinginfo/FundingInfo.java
src/main/java/com/levelUpToast/levelUpToast/domain/product/productinfo/ProductInfo.java
src/main/java/com/levelUpToast/levelUpToast/domain/product/reviwe/Review.java
src/main/java/com/levelUpToast/levelUpToast/domain/product/tag/Tag.java
src/main/java/com/levelUpToast/levelUpToast/domain/product/vendor/Vendor.java

feat (ProductDetail) : ProductDetail.java make

feat (ProductDetail) : Product ProductDetail

---

src/main/java/com/levelUpToast/levelUpToast/domain/product/fundinginfo/FundingInfo.java
src/main/java/com/levelUpToast/levelUpToast/domain/repository/productRepository/productRepositoryImpl/MemoryProductRepository.java
src/main/java/com/levelUpToast/levelUpToast/domain/repository/productRepository/productRepositoryInf/ProductRepository.java
src/main/resources/application.properties

ci (Application.properties ) : Server port Change

---

src/main/resources/application.properties

ci (Application.properties ) : Server ssl test

---

src/main/java/com/levelUpToast/levelUpToast/config/webConfig/WebConfig.java
src/main/java/com/levelUpToast/levelUpToast/domain/dataForm/signUp/SignUpRequestForm.java
src/main/java/com/levelUpToast/levelUpToast/domain/dataForm/signUp/SignUpResponseForm.java
src/main/java/com/levelUpToast/levelUpToast/rest/login/LoginController.java
src/main/java/com/levelUpToast/levelUpToast/rest/signUp/SignUpController.java
src/main/java/com/levelUpToast/levelUpToast/service/e_mail/e_mailServiceImpl/SimpleE_mailService.java
src/main/java/com/levelUpToast/levelUpToast/service/e_mail/e_mailServiceInf/e_mailService.java
src/main/java/com/levelUpToast/levelUpToast/service/img/imgServiceImpl/ImgService_Perriy_MacBook.java
src/main/java/com/levelUpToast/levelUpToast/service/login/loginServiceImpl/SimpleLoginService.java
src/main/java/com/levelUpToast/levelUpToast/service/login/loginServiceInf/LoginService.java
src/main/java/com/levelUpToast/levelUpToast/service/signUp/signUpServiceImpl/SimpleSignUpService.java
src/main/java/com/levelUpToast/levelUpToast/service/signUp/signUpServiceInf/SignUpService.java

* e_mail 서비스 현재 진행 중
* cors 규칙 해결을 위한 webConfig 추가

😎 이메일 서비스 추가 [WIP] 및 webConfig 추가 

---

src/main/resources/application.properties

feat (Application.properties) : mail

---

src/main/java/com/levelUpToast/levelUpToast/domain/mail/Mail.java
src/main/java/com/levelUpToast/levelUpToast/rest/mail/MailController.java
src/main/java/com/levelUpToast/levelUpToast/service/mail/mailServiceImpl/SimpleMailService.java
src/main/java/com/levelUpToast/levelUpToast/service/mail/mailServiceInf/MailService.java

refactor (mail Service) :

---

src/main/java/com/levelUpToast/levelUpToast/rest/mail/MailController.java
src/main/java/com/levelUpToast/levelUpToast/service/mail/mailServiceImpl/SimpleMailService.java

* 변경 사항
* code : UUID 형식 -> 6자리 숫자 코드

😎 메일 인증 서비스 코드 변경 완료

---

src/main/java/com/levelUpToast/levelUpToast/config/token/tokenManager/tokenManagerImpl/SimpleTokenManager.java
src/main/java/com/levelUpToast/levelUpToast/config/token/tokenManager/tokenManagerInf/TokenManager.java

token manger return 타입 
Member 객체 -> Member manageSeq 로 변경

😎 tokenManger return 타입 변경

---

src/main/java/com/levelUpToast/levelUpToast/rest/img/ImgController.java
src/main/java/com/levelUpToast/levelUpToast/rest/mail/MailController.java
src/main/java/com/levelUpToast/levelUpToast/rest/signUp/SignUpController.java
src/main/java/com/levelUpToast/levelUpToast/service/img/imgServiceImpl/SimpleImgService.java
src/main/java/com/levelUpToast/levelUpToast/service/img/imgServiceInf/ImgService.java
src/main/java/com/levelUpToast/levelUpToast/service/login/loginServiceImpl/SimpleLoginService.java
src/main/java/com/levelUpToast/levelUpToast/service/mail/mailServiceImpl/SimpleMailService.java
src/main/java/com/levelUpToast/levelUpToast/service/signUp/signUpServiceImpl/SimpleSignUpService.java

chore (Service, Controller) : rename and code fix, URL fix

☕️Service코드 정리및 코드 수정, Controller URL 규칙 재정의

---

src/main/java/com/levelUpToast/levelUpToast/config/InitData.java
src/main/java/com/levelUpToast/levelUpToast/domain/dataForm/signUp/SignUpRequestForm.java
src/main/java/com/levelUpToast/levelUpToast/domain/member/Member.java
src/main/java/com/levelUpToast/levelUpToast/rest/signUp/SignUpController.java
src/main/java/com/levelUpToast/levelUpToast/service/signUp/signUpServiceImpl/SimpleSignUpService.java

😺회원가입 부분 수정 및 버그 해결

---

src/main/java/com/levelUpToast/levelUpToast/config/InitData.java
src/main/java/com/levelUpToast/levelUpToast/domain/model/img/ImgItem.java
src/main/java/com/levelUpToast/levelUpToast/domain/model/product/productDataForm/ProductDetailResponseForm.java
src/main/java/com/levelUpToast/levelUpToast/domain/model/product/productDataForm/ProductList.java
src/main/java/com/levelUpToast/levelUpToast/domain/model/product/productinfo/ProductInfo.java
src/main/java/com/levelUpToast/levelUpToast/domain/model/vendor/Vendor.java
src/main/java/com/levelUpToast/levelUpToast/domain/repository/imgRepository/imgRepositoryImpl/MemoryImgRepository.java
src/main/java/com/levelUpToast/levelUpToast/domain/repository/imgRepository/imgRepositoryInf/ImgRepository.java
src/main/java/com/levelUpToast/levelUpToast/function/productAdapter/ProductAdapter.java
src/main/java/com/levelUpToast/levelUpToast/function/productAdapter/SimpleProductAdapter.java
src/main/java/com/levelUpToast/levelUpToast/rest/img/ImgController.java
src/main/java/com/levelUpToast/levelUpToast/rest/product/ProductController.java
src/main/java/com/levelUpToast/levelUpToast/rest/product/ProductInspection.java
src/main/java/com/levelUpToast/levelUpToast/rest/product/ProductInspection1.java
src/main/java/com/levelUpToast/levelUpToast/rest/product/SimpleProductInspection.java
src/main/java/com/levelUpToast/levelUpToast/rest/product/SimpleProductInspection1.java
src/main/java/com/levelUpToast/levelUpToast/service/img/imgServiceImpl/SimpleImgService.java
src/main/java/com/levelUpToast/levelUpToast/service/mainPage/MainService.java
src/main/java/com/levelUpToast/levelUpToast/service/mainPage/SimpleMainService.java
src/main/java/com/levelUpToast/levelUpToast/service/product/SimpleProductService.java
src/main/java/com/levelUpToast/levelUpToast/service/search/SearchService.java
src/main/java/com/levelUpToast/levelUpToast/service/search/SimpleSearchService.java
src/main/java/com/levelUpToast/levelUpToast/service/vendor/vendorServiceImpl/SimpleVendorService.java
src/main/java/com/levelUpToast/levelUpToast/service/vendor/vendorServiceInf/VendorService.java

* 변경 이전 : Product 내부 이미지 데이터 값을 UUID 값을 통한 String 형식으로 캡슐화 되어 있음.
* 변경 이후 : Product 내부 이미지 데이터 값을 Long 타입으로 캡슐화 되어 관리되도록 변경됨.
* 변경 사유 : 향후 데이터베이스의 이미지 테이블 컬럼 형식의 맞는 CRUD의 최적화를 위한 리펙토링

😎 이미지 시스템 내부 데이터 관리 방식 리펙토링

---

src/main/java/com/levelUpToast/levelUpToast/rest/product/ProductController.java
src/main/java/com/levelUpToast/levelUpToast/rest/product/ProductInspection.java
src/main/java/com/levelUpToast/levelUpToast/rest/product/SimpleProductInspection.java

Conflict resolved

---

src/main/java/com/levelUpToast/levelUpToast/config/token/tokenManager/tokenManagerInf/TokenManager.java
src/main/java/com/levelUpToast/levelUpToast/controller/SearchController.java
src/main/java/com/levelUpToast/levelUpToast/service/search/GetProductListSearch.java
src/main/java/com/levelUpToast/levelUpToast/util/wordAnalysis/SimpleWordAnalysis.java

fix (Search) : Fixed a bug

---

src/main/java/com/levelUpToast/levelUpToast/config/container/ContainerConfig.java
src/main/java/com/levelUpToast/levelUpToast/controller/HomeController.java
src/main/java/com/levelUpToast/levelUpToast/controller/ProductController.java
src/main/java/com/levelUpToast/levelUpToast/domain/UseCase/home/HomeService.java
src/main/java/com/levelUpToast/levelUpToast/domain/UseCase/member/MemberCheck.java
src/main/java/com/levelUpToast/levelUpToast/domain/UseCase/product/ProblemCheck.java
src/main/java/com/levelUpToast/levelUpToast/domain/UseCase/product/ProductService.java
src/main/java/com/levelUpToast/levelUpToast/domain/UseCase/util/recommendation/Recommendation.java
src/main/java/com/levelUpToast/levelUpToast/service/home/SimpleHomeService.java
src/main/java/com/levelUpToast/levelUpToast/service/login/LoginFindMemberInfo.java
src/main/java/com/levelUpToast/levelUpToast/service/product/SimpleProductService.java
src/main/java/com/levelUpToast/levelUpToast/service/product/UpdateInformationProduct.java
src/main/java/com/levelUpToast/levelUpToast/service/signUp/MemberRegisterSignup.java
src/main/java/com/levelUpToast/levelUpToast/util/member/SimpleMemberCheck.java
src/main/java/com/levelUpToast/levelUpToast/util/product/SimpleProblemCheck.java
src/main/java/com/levelUpToast/levelUpToast/util/recommendation/recommender.java
src/main/resources/application.properties

+ WAS서버 WS서버 분리하여 적용
+ WS서버 포트지정 및 도메인지정

🥹 Application 서버 설정 값 변경

---

src/main/java/com/levelUpToast/levelUpToast/config/InitData.java
src/main/java/com/levelUpToast/levelUpToast/config/token/tokenManager/tokenManagerImpl/SimpleTokenManager.java
src/main/java/com/levelUpToast/levelUpToast/domain/UseCase/member/MemberCheck.java
src/main/java/com/levelUpToast/levelUpToast/domain/UseCase/member/MemberCreate.java
src/main/java/com/levelUpToast/levelUpToast/domain/repository/memberRepository/memberRepositoryImpl/JdbcMemberRepository.java
src/main/java/com/levelUpToast/levelUpToast/domain/repository/memberRepository/memberRepositoryImpl/MemoryMemberRepository.java
src/main/java/com/levelUpToast/levelUpToast/domain/repository/memberRepository/memberRepositoryInf/MemberRepository.java
src/main/java/com/levelUpToast/levelUpToast/service/login/LoginFindMemberInfo.java
src/main/java/com/levelUpToast/levelUpToast/util/member/SimpleMemberCheck.java
src/main/java/com/levelUpToast/levelUpToast/util/member/SimpleMemberCreate.java

resolving conflicts

---

src/main/java/com/levelUpToast/levelUpToast/controller/ProductController.java
src/main/java/com/levelUpToast/levelUpToast/util/product/IsProduct.java
src/main/java/com/levelUpToast/levelUpToast/util/product/SimpleProblemCheck.java

fix (product) : bug fix
